Catkin-ProjectName: object_recognition_reconstruction
Version: 0.2.3
Description: basic 3d reconstruction of an object from aligned Kinect data
Author: Ethan Rublee <erublee@willowgarage.com>, Vincent Rabaud <vrabaud@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  http://ecto.willowgarage.com/recognition

Depends: catkin, ecto, ecto_image_pipeline, object_recognition_core

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
